base:
  project: heart_attack_prediction
  data_dir: data
  data_fname: data.csv
  targ_col: output
  random_state: 42
  model_dir: .mlem/model

data_split:
  test_size: 0.25

train:
  model_type: randomforest
  params:
    n_estimators: 150
    max_depth: 15

eval:
  perm_imp_model_path: models/perm_imp.joblib
