name: heart-attack-model-allFeatures
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md

          
          # Add figure to the report
          echo "## Confusion Matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          
          echo "## ROC curve" >> report.md
          cml-publish ROC_Curve.png --md >> report.md
          
          cml send-comment report.md
