name: heart-attack-model-allFeatures
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull
          dvc repro
          dvc push
          
          # Create CML report
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          
          echo "## Confusion Matrix" >> report.md
          cml publish eval_plots/cm.png --md >> report.md
          
          cml send-comment report.md
